#!/bin/bash

echo 'Inserting secrets...'
source ~/.bashrc;

sed -i "s/WHEREAT_BOSH_AWS_ACCESS_KEY_ID/$WHEREAT_BOSH_AWS_ACCESS_KEY_ID/g" $file
sed -i "s/WHEREAT_BOSH_AWS_ACCESS_KEY_SECRET/$WHEREAT_BOSH_AWS_ACCESS_KEY_SECRET/g" $file
sed -i "s/WHEREAT_BOSH_SUBNET_ID/$WHEREAT_BOSH_SUBNET_ID/g" $file
sed -i "s/WHEREAT_BOSH_SECURITY_GROUP/$WHEREAT_BOSH_SECURITY_GROUP/g" $file
sed -i "s/WHEREAT_BOSH_ELASTIC_IP/$WHEREAT_BOSH_ELASTIC_IP/g" $file
sed -i "s/WHEREAT_CONCOURSE_GITHUB_CLIENT_ID/$WHEREAT_CONCOURSE_GITHUB_CLIENT_ID/g" $file
sed -i "s/WHEREAT_CONCOURSE_GITHUB_CLIENT_SECRET/$WHEREAT_CONCOURSE_GITHUB_CLIENT_SECRET/g" $file
sed -i "s/WHEREAT_CONCOURSE_ELASTIC_IP/$WHEREAT_CONCOURSE_ELASTIC_IP/g" $file
sed -i "s/WHEREAT_CONCOURSE_POSTGRES_PASSWORD/$WHEREAT_CONCOURSE_POSTGRES_PASSWORD/g" $file
