Vagrant.configure('2') do |config|
  config.vm.box = 'cloudfoundry/bosh-lite'

  config.vm.provider :aws do |v, override|
    v.access_key_id = ENV['WHEREAT_BOSH_AWS_ACCESS_KEY_ID'] || ''
    v.secret_access_key = ENV['WHEREAT_BOSH_AWS_SECRET_ACCESS_KEY'] || ''
    v.elastic_ip = ENV['WHEREAT_BOSH_ELASTIC_IP'] || ''
    v.ami = ''
    v.instance_type = 'm3.medium'
  end
end
