azs:
- name: z1
  cloud_properties: {availability_zone: us-east-1a}
- name: z2
  cloud_properties: {availability_zone: us-east-1b}

vm_types:
- name: small
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk: {size: 3000, type: gp2}
- name: medium
  cloud_properties:
    instance_type: m3.medium
    ephemeral_disk: {size: 30000, type: gp2}

disk_types:
- name: small
  disk_size: 3000
  cloud_properties: {type: gp2}
- name: large
  disk_size: 50_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
  # - range: 10.10.0.0/24
  #   gateway: 10.10.0.1
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    az: z1
    # static: [10.0.0.64]
    static: [10.0.0.62]
    reserved: [10.0.0.2 - 10.0.0.9]
    dns: [10.0.0.2]
    cloud_properties: {subnet: WHEREAT_BOSH_SUBNET_ID} # <-- replaced
- name: vip
  type: vip

compilation:
  workers: 1
  reuse_compilation_vms: true
  az: z1
  vm_type: small
  network: private
