---
name: concourse

director_uuid: <%= `bosh status --uuid` %>

releases:
- name: concourse
  version: latest
- name: garden-linux
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: small
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: https://ci.whereat.io # <-- changeable
      publicly_viewable: true
      #development_mode: true
      development_mode: false
      github_auth:
        client_id: WHEREAT_CONCOURSE_GITHUB_CLIENT_ID
        client_secret: WHEREAT_CONCOURSE_GITHUB_CLIENT_SECRET
        authorize:
          - organization: whereat
            teams: [ops]
      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  vm_type: small
  stemcell: trusty
  persistent_disk_type: small
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        role: admin
        password: WHEREAT_CONCOURSE_POSTGRES_PASSWORD # <-- replace

- name: worker
  instances: 1
  vm_type: medium
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-linux
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
